# What is the First Day of the Week?

Whether the Gregorian calendar shows Sunday or Monday as the first day of the week depends on where you live.

Do more countries start the week on Sunday or Monday? What about people? What about by continent?

The file `first-day-of-week.csv` shows the first day of the week for each territory. The file `population.csv` shows the population in the year 2020 for each territory in millions, and the file `four-regions.csv` specifies whether each territory is in asia, europe, africa, or the americas.

In [1]:
# FOR GOOGLE COLAB ONLY.
# Uncomment and run the code below. A dialog will appear to upload files.
# Upload 'first-day-of-week.csv', 'population.csv', and 'four-regions.csv'.

# from google.colab import files
# uploaded = files.upload()

In [2]:
import pandas as pd
df = pd.read_csv('first-day-of-week.csv')
df.head()

        territory alpha3 first_day   units paper
0     Afghanistan    AFG       sat  metric    A4
1   Aland Islands    ALA       mon  metric    A4
2         Albania    ALB       mon  metric    A4
3         Algeria    DZA       sat  metric    A4
4  American Samoa    ASM       sun  metric    A4

In [3]:
pop = pd.read_csv('population.csv')
pop.head()

  alpha3  population
0    AFG       39.07
1    ALB        2.87
2    DZA       44.04
3    AND        0.08
4    AGO       33.45

In [4]:
regions = pd.read_csv('four-regions.csv')
regions.head()

  alpha3 four_regions
0    AUS         asia
1    BRN         asia
2    KHM         asia
3    CHN         asia
4    FJI         asia

### Project Ideas

- How many territories show Friday, Saturday, Sunday, and Monday as the `first_day` of the week?

- How many people start the week on Friday, Saturday, Sunday, and Monday?
	- Hint: This will involve a `merge`.

- Which of the `four_regions` predominantly start the week on Sunday? On Monday? Are there any regions that are more divided between Sunday and Monday?
	- Hint: This will also involve a `merge`.

Question 1: How many territories show Friday, Saturday, Sunday, and Monday as the `first_day` of the week?

In [36]:
df.groupby('first_day').size()

first_day
fri      1
mon    186
sat     15
sun     55
dtype: int64

Question 2:  How many people start the week on Friday, Saturday, Sunday, and Monday?
	- Hint: This will involve a `merge`.

In [53]:
merged = df.merge(pop, on = 'alpha3', how = 'left')
pop_by_fday = merged.groupby('first_day')['population'].sum()
pop_by_fday

first_day
fri       0.50
mon    3600.19
sat     431.79
sun    3844.08
Name: population, dtype: float64

Question 3: Which of the `four_regions` predominantly start the week on Sunday? On Monday? Are there any regions that are more divided between Sunday and Monday?
	- Hint: This will also involve a `merge`.

3.1 Region that predominantly start the week on Sunday:

In [56]:
region = df.merge(regions, on = 'alpha3', how = 'left')
region.query('first_day == "sun"').groupby('four_regions').size()

four_regions
africa       6
americas    20
asia        21
europe       2
dtype: int64

3.2 3.1 Region that predominantly start the week on Monday:

In [60]:
region.query('first_day == "mon"').groupby('four_regions').size()

four_regions
africa      43
americas    15
asia        27
europe      46
dtype: int64

In [62]:
region.query('first_day == ["sun","mon"]').groupby('four_regions').size()

four_regions
africa      49
americas    35
asia        48
europe      48
dtype: int64

3.3 Are there any regions that are more divided between Sunday and Monday?

In [124]:
#Calculating the ratio of sun and mon first day of week for each region
sun_mon = region.query('first_day in ["sun", "mon"]').groupby(['four_regions', 'first_day']).size()
sun_mon = sun_mon.unstack() #creates a matrix
sun_mon

first_day     mon  sun
four_regions
africa         43    6
americas       15   20
asia           27   21
europe         46    2

In [126]:
ratio = abs((sun_mon['sun'] / sun_mon['mon'])-1) #absolute value of the ratio between the two values
ratio

four_regions
africa      0.860465
americas    0.333333
asia        0.222222
europe      0.956522
dtype: float64

Asia is the most divided region between sun and mon as the first day of the week.